import numpy as np
import matplotlib.pyplot as plt

# Load the data generated by C code
data = np.loadtxt('data2.txt')

# Generate the signal values for n = -2 to 2
n_values = np.arange(-1, 3)

# Plot the signal
plt.stem(n_values, data, markerfmt='^', basefmt='k')
plt.xlabel('n')
plt.ylabel('h2[n]')
plt.grid(True)
plt.savefig('fig4.png')
